### ISSUE TITLE
unable to configure using provisioning yaml

### ISSUE THREAD

**Issue by ash1425** [instana/instana-grafana-datasource#71]
I am trying to create docker image which will have preconfigured instana datasource. I am following [this](https://grafana.com/docs/grafana/latest/administration/provisioning/#datasources) guide. 

When I build and run my container it creates the datasource automatically but doesn't show the proper configuration, `url` and `apiToken` are always blank. My configuration yaml is as follows

```
datasources:
  - name: INSTANA-NONPROD
    type: instana-datasource
    access: proxy
    jsonData:
      apiToken: "<API_TOKEN>"
      canQueryOfflineSnapshots: false
      canUseProxy: true
      url: "<Instana URL>"
      useProxy: true
    editable: true
```

<img width="893" alt="Screenshot 2020-05-06 at 9 49 34 PM" src="https://user-images.githubusercontent.com/1128035/81221734-803c3900-8fe3-11ea-9509-768570075487.png">

**Comment by ash1425** [comment]
Sorry, my yaml file was wrong. Deleting the issue. Also sharing correct yaml file

```
# config file version
apiVersion: 1
# list of datasources to insert/update depending
# what's available in the database
datasources:
  # <string, required> name of the datasource. Required
  - name: Instana
    # <string, required> datasource type. Required
    type: instana-datasource
    # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
    access: proxy
    isDefault: true
    jsonData:
      url: "<url>"
      apiToken: "<token>"
      canUseProxy: true
      useProxy: true
    version: 1
    # <bool> allow users to edit datasources from the UI.
    editable: false

```
